[[section-solution-strategy]]

== Descripción de la estrategia del problema
Una de las piedras angulares sobre la que esta basada la aplicación es el almacenamiento descentralizado de la información del usuario. SOLID nos permite llevar a cabo esta administración de datos así que la estructura del proyecto girará en torno a él.
Las características en las que nos centramos para desarrollar la aplicación han la agilidez y la usabildad. Para ello nos centramos en desarrollar una aplicación rápida, intuitiva que ofrezca al usuario una applicación web agradable de utilizar.  

Para ello hemos decido desarrollar este proyecto hemos decidido usar React Native que, además de funcionar perfectamente con SOLID, permite desplegar la aplicación fácilmente tanto en Android como en iOS, permite actualizar componentes rapidamente ante cambios y permite crear aplicaciones muy flexibles.


=== Decisiones tecnológicas
==== Librerías
Las principales librerías a usar son las siguientes:

* React: Biblioteca de Javascript usada para crear el front-end de la aplicación.
* Node.js: Se usa para crear la parte del servidor de la aplicación.
* MongoDB: Es usado a modo de base de datos.
* Leaflet: Se usan los componentes que nos proporciona React-Leaflet para implementar los mapas de la aplicación.
* MaterialUI: Se usa para los aspectos gráfico de la aplicación en lugar de bootstrap.

==== Estructura
Para conseguir que el proyecto sea mantenible su estructura estará basada en contenedores, que serán implementados usando la herramienta Docker.

==== Otras decisiones
Hemos decidido usar Github para el control de versiones. Github tambien permite poder llevar un registro del trabajo realizado por los participantes mediante los pull request.
